name: FabledChat
main: me.symi.chat.FabledChat
version: 0.1
description: This plugin allows players to change their chat message color
author: Symi
api-version: 1.13
website: https://github.com/Symii

commands:
  color:
    aliases: [kolory,kolor,chatcolor,cc]
    usage: /<command>
    description: Use this command to change your chat message color

permissions:
  fabledchat.use:
    description: Allows cc command
    default: false