name: OwnChat
main: me.symi.chat.OwnChat
version: 1.2
description: This plugin allows players to change their chat message color
api-version: 1.16
author: Symi
website: https://github.com/Symii

commands:
  color:
    aliases: [kolory,kolor,chatcolor,cc,oc,ownchat]
    usage: /<command>
    description: Use this command to change your chat message color

permissions:
  ownchat.use:
    description: Allows cc command
    default: false
  ownchat.admin:
    description: Admin permission
    default: op